resources:
- name: my-app
  type: git
  source:
    uri: https://github.com/kalyan3439/my-app.git
    branch: master

jobs:
- name: build-and-test
  plan:
  - get: my-app
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: gradle, tag: latest }
      inputs:
      - name: my-app
      run:
        path: my-app/build.sh  # Adjust this script name accordingly
  - task: test
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: gradle, tag: latest }
      inputs:
      - name: your-java-app-repo
      run:
        path: my-app/test.sh  # Adjust this script name accordingly
